/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6 for MT6582. Copyright MediaTek Inc. (C) 2013.
 * Wed Nov 29 11:36:56 2017
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H




#endif //_CUST_AUXADC_TOOL_H


